// constant/Disclosure/BooksData.js
const booksData = [
  {
    id: 1,
    title: "Advanced Computer Science Principles",
    author: "Dr. Sarah Johnson",
    year: "2023",
    description:
      "Comprehensive guide to modern computer science concepts, algorithms, and system design for advanced learners.",
    pages: 450,
    edition: "3rd",
    category: "Computer Science",
    pdfFile: "/books/advanced-cs-principles.pdf",
    previewLink: "/preview/advanced-cs-principles",
    fileSize: "8.2 MB",
    coverImage: "/images/books/cs-principles.jpg",
  },
  //   {
  //     id: 2,
  //     title: "Research Methodology in Social Sciences",
  //     author: "Prof. Michael Chen",
  //     year: "2022",
  //     description:
  //       "Detailed exploration of qualitative and quantitative research methods with practical examples.",
  //     pages: 320,
  //     edition: "2nd",
  //     category: "Social Sciences",
  //     pdfFile: "/books/research-methodology.pdf",
  //     previewLink: "/preview/research-methodology",
  //     fileSize: "5.6 MB",
  //     coverImage: "/images/books/research-methodology.jpg",
  //   },
  //   {
  //     id: 3,
  //     title: "Modern Business Management",
  //     author: "Dr. Robert Williams",
  //     year: "2024",
  //     description:
  //       "Contemporary approaches to business management, leadership, and organizational strategy.",
  //     pages: 380,
  //     edition: "1st",
  //     category: "Business",
  //     pdfFile: "/books/business-management.pdf",
  //     previewLink: "/preview/business-management",
  //     fileSize: "7.1 MB",
  //     coverImage: "/images/books/business-management.jpg",
  //   },
  //   {
  //     id: 4,
  //     title: "Environmental Science & Sustainability",
  //     author: "Dr. Emma Wilson",
  //     year: "2023",
  //     description:
  //       "Comprehensive study of environmental systems, conservation, and sustainable development.",
  //     pages: 420,
  //     edition: "2nd",
  //     category: "Environmental",
  //     pdfFile: "/books/environmental-science.pdf",
  //     previewLink: "/preview/environmental-science",
  //     fileSize: "9.3 MB",
  //     coverImage: "/images/books/environmental-science.jpg",
  //   },
  //   {
  //     id: 5,
  //     title: "Digital Marketing Strategies",
  //     author: "Alex Thompson",
  //     year: "2024",
  //     description:
  //       "Latest digital marketing techniques, SEO optimization, and social media strategies.",
  //     pages: 280,
  //     edition: "1st",
  //     category: "Marketing",
  //     pdfFile: "/books/digital-marketing.pdf",
  //     previewLink: "/preview/digital-marketing",
  //     fileSize: "4.8 MB",
  //   },
  //   {
  //     id: 6,
  //     title: "Medical Biotechnology Advances",
  //     author: "Dr. Lisa Rodriguez",
  //     year: "2023",
  //     description:
  //       "Cutting-edge research in medical biotechnology and therapeutic applications.",
  //     pages: 510,
  //     edition: "4th",
  //     category: "Biotechnology",
  //     pdfFile: "/books/medical-biotech.pdf",
  //     previewLink: "/preview/medical-biotech",
  //     fileSize: "11.2 MB",
  //     coverImage: "/images/books/medical-biotech.jpg",
  //   },
  //   {
  //     id: 7,
  //     title: "Artificial Intelligence Fundamentals",
  //     author: "Dr. James Miller",
  //     year: "2024",
  //     description:
  //       "Introduction to AI concepts, machine learning algorithms, and neural networks.",
  //     pages: 360,
  //     edition: "2nd",
  //     category: "Artificial Intelligence",
  //     pdfFile: "/books/ai-fundamentals.pdf",
  //     previewLink: "/preview/ai-fundamentals",
  //     fileSize: "6.5 MB",
  //   },
  //   {
  //     id: 8,
  //     title: "Financial Mathematics",
  //     author: "Prof. David Brown",
  //     year: "2022",
  //     description:
  //       "Mathematical foundations of finance, risk assessment, and investment strategies.",
  //     pages: 400,
  //     edition: "3rd",
  //     category: "Finance",
  //     pdfFile: "/books/financial-math.pdf",
  //     previewLink: "/preview/financial-math",
  //     fileSize: "7.9 MB",
  //     coverImage: "/images/books/financial-math.jpg",
  //   },
];

export default booksData;
