// constant/Infocorner/ReportsData.js
const reportsData = [
  {
    id: 1,
    title: "Annual Report 2023-24",
    type: "Annual",
    year: "2023-24",
    description:
      "Comprehensive annual report covering all institutional activities, achievements, and future plans.",
    pdfFile: "/reports/annual-2023-24.pdf",
    fileSize: "15.2 MB",
    pages: "120 pages",
    publishedDate: "March 15, 2024",
    fileFormat: "PDF",
    hasSummary: true,
    summaryLink: "/reports/summary-annual-2023-24.pdf",
    externalLink: "https://portal.example.com/annual-report-2023",
    isMandatory: true,
  },
  {
    id: 2,
    title: "Financial Audit Report 2023",
    type: "Financial",
    year: "2023",
    description:
      "Complete financial audit report with balance sheets, income statements, and audit notes.",
    pdfFile: "/reports/financial-audit-2023.pdf",
    fileSize: "8.7 MB",
    pages: "85 pages",
    publishedDate: "February 28, 2024",
    fileFormat: "PDF",
    quarter: 4,
    isMandatory: true,
  },
  {
    id: 3,
    title: "Academic Performance Report",
    type: "Academic",
    year: "2023-24",
    description:
      "Detailed analysis of student performance, faculty achievements, and academic programs.",
    pdfFile: "/reports/academic-performance-2024.pdf",
    fileSize: "6.3 MB",
    pages: "65 pages",
    publishedDate: "April 10, 2024",
    fileFormat: "PDF",
    hasSummary: true,
    summaryLink: "/reports/summary-academic-2024.pdf",
  },
  {
    id: 4,
    title: "Research Publications Report",
    type: "Research",
    year: "2023",
    description:
      "Compilation of research papers, projects, and publications from faculty and students.",
    pdfFile: "/reports/research-publications-2023.pdf",
    fileSize: "12.5 MB",
    pages: "95 pages",
    publishedDate: "January 20, 2024",
    fileFormat: "PDF",
    externalLink: "https://research.example.com/publications-2023",
  },
  {
    id: 5,
    title: "Q3 Financial Report 2023",
    type: "Financial",
    year: "2023",
    description:
      "Third quarter financial performance and budget utilization report.",
    pdfFile: "/reports/financial-q3-2023.pdf",
    fileSize: "5.1 MB",
    pages: "45 pages",
    publishedDate: "October 15, 2023",
    fileFormat: "PDF",
    quarter: 3,
  },
  {
    id: 6,
    title: "Annual Report 2022-23",
    type: "Annual",
    year: "2022-23",
    description:
      "Previous year's comprehensive annual report for institutional reference.",
    pdfFile: "/reports/annual-2022-23.pdf",
    fileSize: "14.8 MB",
    pages: "118 pages",
    publishedDate: "March 10, 2023",
    fileFormat: "PDF",
    hasSummary: true,
    summaryLink: "/reports/summary-annual-2022-23.pdf",
    isMandatory: true,
  },
  {
    id: 7,
    title: "Student Enrollment Statistics",
    type: "Academic",
    year: "2024",
    description:
      "Detailed enrollment data, demographic analysis, and admission trends.",
    pdfFile: "/reports/enrollment-stats-2024.pdf",
    fileSize: "4.2 MB",
    pages: "38 pages",
    publishedDate: "May 5, 2024",
    fileFormat: "PDF",
  },
  {
    id: 8,
    title: "Infrastructure Development Report",
    type: "Annual",
    year: "2023-24",
    description:
      "Report on new infrastructure projects, facilities development, and campus upgrades.",
    pdfFile: "/reports/infrastructure-2024.pdf",
    fileSize: "9.6 MB",
    pages: "72 pages",
    publishedDate: "June 1, 2024",
    fileFormat: "PDF",
    externalLink: "https://campus.example.com/development-2024",
  },
  {
    id: 9,
    title: "Research Grant Utilization Report",
    type: "Research",
    year: "2023",
    description:
      "Report on research grants received, utilization, and outcomes achieved.",
    pdfFile: "/reports/research-grants-2023.pdf",
    fileSize: "7.8 MB",
    pages: "68 pages",
    publishedDate: "December 15, 2023",
    fileFormat: "PDF",
    isMandatory: true,
  },
];

export default reportsData;
