// constant/Admission/admissionEnquiryFormData.js
export const admissionEnquiryFormData = {
  title: "Admission Enquiry Form",
  description:
    "Begin your child's educational journey with us. Fill out the form below and our admission team will get in touch with you shortly.",

  formFields: [
    {
      id: "fullName",
      label: "Full Name",
      name: "fullName",
      type: "text",
      placeholder: "Enter Full name",
      icon: "user",
      required: true,
      gridColumn: "left",
    },
    {
      id: "dateOfBirth",
      label: "Date of Birth",
      name: "dateOfBirth",
      type: "date",
      placeholder: "Enter Your Date of Birth",
      icon: "calendar",
      required: true,
      gridColumn: "left",
    },
    {
      id: "admissionClass",
      label: "Admission in Class",
      name: "admissionClass",
      type: "select",
      placeholder: "--SELECT CLASS--",
      icon: "school",
      required: true,
      options: [
        "SELECT CLASS",
        "Nursery",
        "Junior KG",
        "Senior KG",
        "Grade 1",
        "Grade 2",
        "Grade 3",
        "Grade 4",
        "Grade 5",
        "Grade 6",
        "Grade 7",
        "Grade 8",
        "Grade 9",
        "Grade 10",
        "Grade 11",
        "Grade 12",
      ],
      gridColumn: "left",
    },
    {
      id: "lastExam",
      label: "Last Examination passed/appeared",
      name: "lastExam",
      type: "text",
      placeholder: "Enter Last Examination passed/appeared",
      icon: "book-open",
      required: true,
      gridColumn: "left",
    },
    {
      id: "fatherName",
      label: "Full name of the Father",
      name: "fatherName",
      type: "text",
      placeholder: "Enter Father Name",
      icon: "user-circle",
      required: true,
      gridColumn: "right",
    },
    {
      id: "email",
      label: "Your Email",
      name: "email",
      type: "email",
      placeholder: "Email",
      icon: "mail",
      required: true,
      gridColumn: "right",
    },
    {
      id: "mobileNo",
      label: "Your Mobile No.",
      name: "mobileNo",
      type: "tel",
      placeholder: "Enter Mobile No.",
      icon: "phone",
      required: true,
      gridColumn: "right",
    },
    {
      id: "additionalInfo",
      label: "Additional Information (Optional)",
      name: "additionalInfo",
      type: "textarea",
      placeholder: "Any specific queries or information you'd like to share...",
      icon: "file-text",
      required: false,
      rows: 3,
      gridColumn: "right",
    },
  ],

  note: "Our admission team typically responds within 24 hours on working days. Please ensure all information provided is accurate. For urgent queries, please call our admission office directly.",

  contactInfo: [
    {
      icon: "clock",
      title: "Response Time",
      value: "24-48 hours",
      description:
        "Our admission team responds to all enquiries within 24-48 working hours.",
    },
    {
      icon: "phone",
      title: "Direct Contact",
      value: "+91-XXXXXXXXXX",
      description:
        "For urgent queries, call our admission office during working hours.",
    },
    {
      icon: "calendar",
      title: "Office Hours",
      value: "Mon-Fri, 9 AM - 5 PM",
      description:
        "Visit our campus for a personalized tour and counselling session.",
    },
  ],
};
